gateways:
  motherduck:
    connection:
      type: motherduck
      catalogs:
        bill_import: "md:bill_import"
        ephemeral: ":memory:"
      token: {{ env_var('MOTHERDUCK_TOKEN') }}

default_gateway: motherduck

model_defaults:
  dialect: duckdb
  start: 2025-04-28